### ISSUE TITLE
pyo3_runtime.PanicException: attempt to divide by zero

### ISSUE THREAD

**Issue by nashanghenzan** [apcamargo/magpurify2#3]
hi， i have a new issue now, the detail is follow:
```
(magpurify2) [root@centos7-02-66b664b9d9-gz85w kegg]# magpurify2 coverage /mnt/semibin/checkm/sort/c50_x10.bin/* /mnt/semibin/purify --bam_files /mnt/semibin/mapped_sorted_bam/*.bam -t 15
[2023-05-15 10:19:59] INFO: MAGpurify2 v1.0.0
[2023-05-15 10:19:59] INFO: magpurify2 coverage /mnt/semibin/checkm/sort/c50_x10.bin/GHB_bin.0.fa /mnt/semibin/checkm/sort/c50_x10.bin/GHB_bin.3.fa /mnt/semibin/checkm/sort/c50_x10.bin/GHB_bin.4.fa /mnt/semibin/checkm/sort/c50_x10.bin/GHB_bin.6.fa /mnt/semibin/checkm/sort/c50_x10.bin/GHB_bin.9.fa /mnt/semibin/checkm/sort/c50_x10.bin/GHR_bin.3.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHB_bin.18.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHB_bin.4.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHB_bin.9.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHR_bin.0.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHR_bin.1.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHR_bin.19.fa /mnt/semibin/checkm/sort/c50_x10.bin/LHR_bin.6.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.0.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.1.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.10.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.12.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.16.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.19.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSB_bin.20.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSR_bin.1.fa /mnt/semibin/checkm/sort/c50_x10.bin/LSR_bin.8.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHB_bin.1.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHB_bin.16.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHB_bin.4.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHB_bin.9.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHR_bin.12.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHR_bin.17.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHR_bin.18.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHR_bin.19.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHR_bin.23.fa /mnt/semibin/checkm/sort/c50_x10.bin/PHR_bin.5.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.0.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.10.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.13.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.16.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.18.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.2.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.20.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.3.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.6.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSB_bin.7.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSR_bin.15.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSR_bin.24.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSR_bin.29.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSR_bin.45.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSR_bin.7.fa /mnt/semibin/checkm/sort/c50_x10.bin/PSR_bin.82.fa /mnt/semibin/checkm/sort/c50_x10.bin/SHB_bin.5.fa /mnt/semibin/checkm/sort/c50_x10.bin/SHB_bin.7.fa /mnt/semibin/checkm/sort/c50_x10.bin/SHR_bin.0.fa /mnt/semibin/checkm/sort/c50_x10.bin/SSB_bin.0.fa /mnt/semibin/checkm/sort/c50_x10.bin/SSB_bin.17.fa /mnt/semibin/checkm/sort/c50_x10.bin/SSB_bin.9.fa /mnt/semibin/checkm/sort/c50_x10.bin/SSR_bin.2.fa /mnt/semibin/checkm/sort/c50_x10.bin/THB_bin.11.fa /mnt/semibin/checkm/sort/c50_x10.bin/THB_bin.14.fa /mnt/semibin/checkm/sort/c50_x10.bin/THB_bin.15.fa /mnt/semibin/checkm/sort/c50_x10.bin/THB_bin.8.fa /mnt/semibin/checkm/sort/c50_x10.bin/THB_bin.9.fa /mnt/semibin/checkm/sort/c50_x10.bin/THR_bin.1.fa /mnt/semibin/checkm/sort/c50_x10.bin/THR_bin.17.fa /mnt/semibin/checkm/sort/c50_x10.bin/THR_bin.25.fa /mnt/semibin/checkm/sort/c50_x10.bin/THR_bin.3.fa /mnt/semibin/checkm/sort/c50_x10.bin/THR_bin.34.fa /mnt/semibin/checkm/sort/c50_x10.bin/THR_bin.5.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSB_bin.11.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSB_bin.18.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSB_bin.2.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSB_bin.23.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSB_bin.3.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSB_bin.7.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.13.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.16.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.2.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.25.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.28.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.36.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.39.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.4.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.6.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.70.fa /mnt/semibin/checkm/sort/c50_x10.bin/TSR_bin.9.fa /mnt/semibin/purify --bam_files /mnt/semibin/mapped_sorted_bam/GHB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/GHR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/GSB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/GSR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/LHB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/LHR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/LSB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/LSR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/PHB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/PHR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/PSB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/PSR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/SHB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/SHR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/SSB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/SSR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/THB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/THR.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/TSB.mapped.sorted.bam /mnt/semibin/mapped_sorted_bam/TSR.mapped.sorted.bam -t 15
[2023-05-15 10:19:59] INFO: Executing MAGpurify2 coverage module.
[2023-05-15 10:20:01] INFO: Reading 83 genomes.
[2023-05-15 10:20:05] INFO: Computing contig coverages from 20 BAM files.
thread '<unnamed>' panicked at 'attempt to divide by zero', src/coverage.rs:196:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/root/miniconda3/envs/magpurify2/bin/magpurify2", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/cli.py", line 153, in cli
    args.func(args)
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/modules/coverage.py", line 98, in main
    threads=args.threads,
pyo3_runtime.PanicException: attempt to divide by zero
```

**Comment by apcamargo** [comment]
Are the BAM files sorted?

**Comment by nashanghenzan** [comment]
> Are the BAM files sorted?

yes, they were all sorted and indexed.

**Comment by apcamargo** [comment]
Did you map the reads to the same contigs that are in your MAGs? The names of the sequences in the MAGs must match those of the reference sequences in your BAMs.

**Comment by nashanghenzan** [comment]
> Did you map the reads to the same contigs that are in your MAGs? The names of the sequences in the MAGs must match those of the reference sequences in your BAMs.

thanks for your reply, i found my MAGs sequance name have changed by semibin, i will try again.
