### ISSUE TITLE
The input integer is not a valid NCBI taxonomic identifier

### ISSUE THREAD

**Issue by nashanghenzan** [apcamargo/magpurify2#4]
```
magpurify2 taxonomy /mnt/semibin/purify/bin/* /mnt/semibin/purify /mnt/shujuku/magpurify2/magpurify2DB -t 15
[2023-05-15 22:00:52] INFO: MAGpurify2 v1.0.0
[2023-05-15 22:00:52] INFO: magpurify2 taxonomy /mnt/semibin/purify/bin/GHB_bin.0.fa /mnt/semibin/purify/bin/GHB_bin.4.fa /mnt/semibin/purify/bin/GHB_bin.6.fa /mnt/semibin/purify/bin/GHB_bin.9.fa /mnt/semibin/purify/bin/GHR_bin.3.fa /mnt/semibin/purify/bin/LHB_bin.18.fa /mnt/semibin/purify/bin/LHB_bin.9.fa /mnt/semibin/purify/bin/LHR_bin.1.fa /mnt/semibin/purify/bin/LHR_bin.19.fa /mnt/semibin/purify/bin/LHR_bin.6.fa /mnt/semibin/purify/bin/LSB_bin.0.fa /mnt/semibin/purify/bin/LSB_bin.1.fa /mnt/semibin/purify/bin/LSB_bin.10.fa /mnt/semibin/purify/bin/LSB_bin.16.fa /mnt/semibin/purify/bin/LSB_bin.19.fa /mnt/semibin/purify/bin/LSB_bin.20.fa /mnt/semibin/purify/bin/LSR_bin.1.fa /mnt/semibin/purify/bin/LSR_bin.8.fa /mnt/semibin/purify/bin/PHB_bin.16.fa /mnt/semibin/purify/bin/PHB_bin.9.fa /mnt/semibin/purify/bin/PHR_bin.12.fa /mnt/semibin/purify/bin/PHR_bin.17.fa /mnt/semibin/purify/bin/PHR_bin.18.fa /mnt/semibin/purify/bin/PHR_bin.19.fa /mnt/semibin/purify/bin/PHR_bin.5.fa /mnt/semibin/purify/bin/PSB_bin.0.fa /mnt/semibin/purify/bin/PSB_bin.10.fa /mnt/semibin/purify/bin/PSB_bin.13.fa /mnt/semibin/purify/bin/PSB_bin.16.fa /mnt/semibin/purify/bin/PSB_bin.18.fa /mnt/semibin/purify/bin/PSB_bin.2.fa /mnt/semibin/purify/bin/PSB_bin.20.fa /mnt/semibin/purify/bin/PSB_bin.6.fa /mnt/semibin/purify/bin/PSB_bin.7.fa /mnt/semibin/purify/bin/PSR_bin.24.fa /mnt/semibin/purify/bin/PSR_bin.29.fa /mnt/semibin/purify/bin/PSR_bin.45.fa /mnt/semibin/purify/bin/PSR_bin.82.fa /mnt/semibin/purify/bin/SHR_bin.0.fa /mnt/semibin/purify/bin/SSB_bin.17.fa /mnt/semibin/purify/bin/SSR_bin.2.fa /mnt/semibin/purify/bin/THB_bin.14.fa /mnt/semibin/purify/bin/THB_bin.15.fa /mnt/semibin/purify/bin/THB_bin.9.fa /mnt/semibin/purify/bin/THR_bin.1.fa /mnt/semibin/purify/bin/THR_bin.25.fa /mnt/semibin/purify/bin/THR_bin.3.fa /mnt/semibin/purify/bin/THR_bin.34.fa /mnt/semibin/purify/bin/THR_bin.5.fa /mnt/semibin/purify/bin/TSB_bin.11.fa /mnt/semibin/purify/bin/TSB_bin.2.fa /mnt/semibin/purify/bin/TSB_bin.23.fa /mnt/semibin/purify/bin/TSB_bin.3.fa /mnt/semibin/purify/bin/TSB_bin.7.fa /mnt/semibin/purify/bin/TSR_bin.13.fa /mnt/semibin/purify/bin/TSR_bin.16.fa /mnt/semibin/purify/bin/TSR_bin.2.fa /mnt/semibin/purify/bin/TSR_bin.25.fa /mnt/semibin/purify/bin/TSR_bin.36.fa /mnt/semibin/purify/bin/TSR_bin.39.fa /mnt/semibin/purify/bin/TSR_bin.4.fa /mnt/semibin/purify/bin/TSR_bin.6.fa /mnt/semibin/purify/bin/TSR_bin.70.fa /mnt/semibin/purify/bin/TSR_bin.9.fa /mnt/semibin/purify /mnt/shujuku/magpurify2/magpurify2DB -t 15
[2023-05-15 22:00:52] INFO: Executing MAGpurify2 taxonomy module.
[2023-05-15 22:00:52] INFO: Using database 'magpurify2DB' version 1.0.
[2023-05-15 22:00:52] INFO: Reading 64 genomes.
[2023-05-15 22:00:59] INFO: Predicting proteins from 64 genomes using Prodigal.
[2023-05-15 22:04:57] INFO: Writing MMseqs2 input file to: '/mnt/semibin/purify/mmseqs2/mmseqs2_input.faa'.
[2023-05-15 22:05:48] INFO: Running MMseqs2 for gene taxonomic assignment.
[2023-05-15 23:46:29] INFO: Reading MMseqs2 output files.
[2023-05-15 23:46:32] INFO: Computing contig scores.
Traceback (most recent call last):
  File "/root/miniconda3/envs/magpurify2/bin/magpurify2", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/cli.py", line 153, in cli
    args.func(args)
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/modules/taxonomy.py", line 116, in main
    for mag in mag_list
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/modules/taxonomy.py", line 116, in <listcomp>
    for mag in mag_list
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/core.py", line 375, in __init__
    min_genus_identity=min_genus_identity
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/core.py", line 397, in get_gene_taxonomy
    taxon = taxopy.Taxon(str(self.taxid_array[i][j]), self.taxdb)
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/taxopy/core.py", line 274, in __init__
    "The input integer is not a valid NCBI taxonomic identifier."
taxopy.exceptions.TaxidError: The input integer is not a valid NCBI taxonomic identifier.
```

**Comment by apcamargo** [comment]
Can you attach the MMseqs2 output files?

- `/mnt/semibin/purify/mmseqs2/mmseqs2_taxonomy.tsv`
- `/mnt/semibin/purify/mmseqs2/mmseqs2_alignment.tsv`

**Comment by nashanghenzan** [comment]
> Can you attach the MMseqs2 output files?
> 
> * `/mnt/semibin/purify/mmseqs2/mmseqs2_taxonomy.tsv`
> * `/mnt/semibin/purify/mmseqs2/mmseqs2_alignment.tsv`
they can be found in follow link
https://github.com/nashanghenzan/issue-files

**Comment by apcamargo** [comment]
Thanks!

I just uploaded version 1.0.1 to PyPI. Can you check if it fixes your issue?

**Comment by nashanghenzan** [comment]
> Thanks!
> 
> I just uploaded version 1.0.1 to PyPI. Can you check if it fixes your issue?

i have another issue when use filter Module:
```
(magpurify2) [root@centos7-02-66b664b9d9-gz85w purify]# magpurify2 filter /mnt/semibin/purify/bin/* /mnt/semibin/purify /mnt/semibin/purify/filtered_genomes -t 15
[2023-05-16 09:43:47] INFO: MAGpurify2 v1.0.1
[2023-05-16 09:43:47] INFO: magpurify2 filter /mnt/semibin/purify/bin/GHB_bin.0.fa /mnt/semibin/purify/bin/GHB_bin.4.fa /mnt/semibin/purify/bin/GHB_bin.6.fa /mnt/semibin/purify/bin/GHB_bin.9.fa /mnt/semibin/purify/bin/GHR_bin.3.fa /mnt/semibin/purify/bin/LHB_bin.18.fa /mnt/semibin/purify/bin/LHB_bin.9.fa /mnt/semibin/purify/bin/LHR_bin.1.fa /mnt/semibin/purify/bin/LHR_bin.19.fa /mnt/semibin/purify/bin/LHR_bin.6.fa /mnt/semibin/purify/bin/LSB_bin.0.fa /mnt/semibin/purify/bin/LSB_bin.1.fa /mnt/semibin/purify/bin/LSB_bin.10.fa /mnt/semibin/purify/bin/LSB_bin.16.fa /mnt/semibin/purify/bin/LSB_bin.19.fa /mnt/semibin/purify/bin/LSB_bin.20.fa /mnt/semibin/purify/bin/LSR_bin.1.fa /mnt/semibin/purify/bin/LSR_bin.8.fa /mnt/semibin/purify/bin/PHB_bin.16.fa /mnt/semibin/purify/bin/PHB_bin.9.fa /mnt/semibin/purify/bin/PHR_bin.12.fa /mnt/semibin/purify/bin/PHR_bin.17.fa /mnt/semibin/purify/bin/PHR_bin.18.fa /mnt/semibin/purify/bin/PHR_bin.19.fa /mnt/semibin/purify/bin/PHR_bin.5.fa /mnt/semibin/purify/bin/PSB_bin.0.fa /mnt/semibin/purify/bin/PSB_bin.10.fa /mnt/semibin/purify/bin/PSB_bin.13.fa /mnt/semibin/purify/bin/PSB_bin.16.fa /mnt/semibin/purify/bin/PSB_bin.18.fa /mnt/semibin/purify/bin/PSB_bin.2.fa /mnt/semibin/purify/bin/PSB_bin.20.fa /mnt/semibin/purify/bin/PSB_bin.6.fa /mnt/semibin/purify/bin/PSB_bin.7.fa /mnt/semibin/purify/bin/PSR_bin.24.fa /mnt/semibin/purify/bin/PSR_bin.29.fa /mnt/semibin/purify/bin/PSR_bin.45.fa /mnt/semibin/purify/bin/PSR_bin.82.fa /mnt/semibin/purify/bin/SHR_bin.0.fa /mnt/semibin/purify/bin/SSB_bin.17.fa /mnt/semibin/purify/bin/SSR_bin.2.fa /mnt/semibin/purify/bin/THB_bin.14.fa /mnt/semibin/purify/bin/THB_bin.15.fa /mnt/semibin/purify/bin/THB_bin.9.fa /mnt/semibin/purify/bin/THR_bin.1.fa /mnt/semibin/purify/bin/THR_bin.25.fa /mnt/semibin/purify/bin/THR_bin.3.fa /mnt/semibin/purify/bin/THR_bin.34.fa /mnt/semibin/purify/bin/THR_bin.5.fa /mnt/semibin/purify/bin/TSB_bin.11.fa /mnt/semibin/purify/bin/TSB_bin.2.fa /mnt/semibin/purify/bin/TSB_bin.23.fa /mnt/semibin/purify/bin/TSB_bin.3.fa /mnt/semibin/purify/bin/TSB_bin.7.fa /mnt/semibin/purify/bin/TSR_bin.13.fa /mnt/semibin/purify/bin/TSR_bin.16.fa /mnt/semibin/purify/bin/TSR_bin.2.fa /mnt/semibin/purify/bin/TSR_bin.25.fa /mnt/semibin/purify/bin/TSR_bin.36.fa /mnt/semibin/purify/bin/TSR_bin.39.fa /mnt/semibin/purify/bin/TSR_bin.4.fa /mnt/semibin/purify/bin/TSR_bin.6.fa /mnt/semibin/purify/bin/TSR_bin.70.fa /mnt/semibin/purify/bin/TSR_bin.9.fa /mnt/semibin/purify /mnt/semibin/purify/filtered_genomes -t 15
[2023-05-16 09:43:47] INFO: Reading 64 genomes.
[2023-05-16 09:43:50] INFO: Reading contig scores from the composition, coverage, codon_usage, taxonomy modules.
[2023-05-16 09:43:53] INFO: Estimating contamination probabilities and identifying contaminant contigs.
Traceback (most recent call last):
  File "/root/miniconda3/envs/magpurify2/bin/magpurify2", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/cli.py", line 153, in cli
    args.func(args)
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/modules/filter.py", line 148, in main
    args.threads,
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/core.py", line 543, in __init__
    model.load_model(model_file)
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/xgboost/core.py", line 2170, in load_model
    self.handle, c_str(fname)))
  File "/root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/xgboost/core.py", line 218, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [09:43:53] ../src/common/io.cc:102: Opening /root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/magpurify2/models/full_model.json failed: No such file or directory
Stack trace:
  [bt] (0) /root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(+0xc94ed) [0x7fac290144ed]
  [bt] (1) /root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(+0xc9ada) [0x7fac29014ada]
  [bt] (2) /root/miniconda3/envs/magpurify2/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(XGBoosterLoadModel+0x379) [0x7fac28fe99b9]
  [bt] (3) /root/miniconda3/envs/magpurify2/lib/python3.7/lib-dynload/../../libffi.so.8(+0xa052) [0x7fac60ec1052]
  [bt] (4) /root/miniconda3/envs/magpurify2/lib/python3.7/lib-dynload/../../libffi.so.8(+0x8925) [0x7fac60ebf925]
  [bt] (5) /root/miniconda3/envs/magpurify2/lib/python3.7/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fac60ec006e]
  [bt] (6) /root/miniconda3/envs/magpurify2/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2f4) [0x7fac60ed87b4]
  [bt] (7) /root/miniconda3/envs/magpurify2/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x1102c) [0x7fac60ed902c]
  [bt] (8) /root/miniconda3/envs/magpurify2/bin/python(_PyObject_FastCallKeywords+0x3cb) [0x55ca44359dcb]
```

**Comment by apcamargo** [comment]
Just fixed the issue. Can you try the new version (1.0.2)?

**Comment by nashanghenzan** [comment]
ok，it works successfuly, many thanks.
